# Generated by Django 5.1.7 on 2025-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_records', to='website.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_record', to='website.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_record', to='website.course')),
            ],
        ),
    ]
